server:
  host: "0.0.0.0"
  port:
    http: 8080
queue:
  urls: [
    "nats://nats-node1:4222",
    "nats://nats-node2:4222",
    "nats://nats-node3:4222",
  ]
  username: "shop_svc"
  password: "super_duper_secret_key"
db:
  driver: "postgres"
  user: "postgres"
  password: "postgres"
  hostdb: "postgres"
  portdb: 5432
  dbname: "postgres"
  mode: "disable"
scheduler:
  time_fetch: 30
  limit: 10
